apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  namespace: dev
spec:
  replicas: 2  #we go with two replicas and two pods running initially
  selector:
    matchLabels:
      app: rjobert-playground
  template:
    metadata:
      labels:
        app: rjobert-playground
    spec:
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: rjobert-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
